service:
  port: 10080
  version: 1.0.0
  jwt_secret: "vvSRkP7Zxssp3UZCw7DBiI1Fk0lfm/i3OqKv8zQKh/w="

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "client_db"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: 123456
  dbname: 0
  network: "tcp"

node:
  node_id: 1